---
author: Sarah Zeller
title: Awesome presentation
subtitle: Cool seminar
date: today

format: 
  tud-beamer: default

bibliography: references.bib
---

# In the morning

## Getting up

-   Turn off alarm
-   Get out of bed

## Breakfast

-   Eat eggs
-   Drink coffee

# In the evening

## Dinner

-   Eat spaghetti
-   Drink wine

## Going to sleep

-   Get in bed
    -   Count sheep
    -   Count even more sheep

-   Add a reference to your \LaTeX-template [@tidyverse]

## References {.allowframebreaks}

::: {#refs}
:::

# Appendix

## A graph for the `mtcars` dataset

```{r}
#| label: fig-mtcars
#| fig-height: 5
#| fig-cap: Horse power correlates with miles per gallon.
library(ggplot2)
mtcars |> 
  ggplot() +
  geom_point(aes(x = mpg, y = hp, col = cyl)) +
  labs(x = "Miles per gallon",
       y = "Horse power",
       col = "Cylinders",
       caption = "Data: {datasets}") +
  theme_minimal()
```

## A table for the `mtcars` dataset

```{r}
#| label: tabl-mtcars
##| tbl-cap: Summary statistics for `mtcars`

library(modelsummary)
mtcars |> 
  datasummary_skim()
```

